---
abstract: 'use FastCGI with L<IO::Async>'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  Test::HexString: 0
  Test::More: 0
  Test::Refcount: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4001, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Async-FastCGI
provides:
  Net::Async::FastCGI:
    file: lib/Net/Async/FastCGI.pm
    version: 0.25
  Net::Async::FastCGI::PSGI:
    file: lib/Net/Async/FastCGI/PSGI.pm
    version: 0.25
  Net::Async::FastCGI::Protocol:
    file: lib/Net/Async/FastCGI/Protocol.pm
    version: 0.25
  Net::Async::FastCGI::Request:
    file: lib/Net/Async/FastCGI/Request.pm
    version: 0.25
  Net::Async::FastCGI::ServerProtocol:
    file: lib/Net/Async/FastCGI/ServerProtocol.pm
    version: 0
  Plack::Handler::Net::Async::FastCGI:
    file: lib/Plack/Handler/Net/Async/FastCGI.pm
    version: 0.25
requires:
  Encode: 0
  Exporter: 5.57
  HTTP::Request: 0
  HTTP::Response: 0
  IO::Async::Listener: 0.35
  IO::Async::Loop: 0.16
  IO::Async::Protocol::Stream: 0.33
  IO::Async::Test: 0
  Net::FastCGI::Constant: 0.10
  Net::FastCGI::Protocol: 0.10
  Tie::Handle: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.25
